### PR TITLE
Some modifications in the third Notebook

### PR DESCRIPTION
**Pull request by mesnardo**
- in function `forward_diff()`: use the array attribute `size` instead of `len()`
  and adapt the markdown cell just below it, accordingly;
- add reference to Numpy function `numpy.allclose()`;
- add consistency between the two cells plotting with Matplotlib
  (`pyplot.xlim()`, `color`, `linestyle`);
- use `label` kwarg in `pyplot.plot` instead of in `pyplot.legend()`;
- use `str.format()` to print;
- use `from bokeh import plotting as bplotting` to not risk possible namespace conflicts
  when using `figure()` and `show()`.

### CODE REVIEW

**Comment by gforsyth** [comment]
Looks good, @mesnardo -- did we want to swap out the for loop for slicing or leave as is?

**Comment by mesnardo** [comment]
@gforsyth -- I think the vanilla code (with `for` loop) is good for `%timeit` comparison. Also, on my laptop, I got faster results with my slided `forward_diff()` than the `numpy.diff()` division.

**Comment by gforsyth** [comment]
ha.  ok, that doesn't make for a good learning experience.  merging now.

**Comment by labarba** [comment]
> use `str.format()` to print

I see no difference in the appearance of the output with the modified call to `print()`. For example, on input cell 9, the previous code had `print('Exact integral:', exact_integral)` … the new code has `print('Exact integral: {}'.format(exact_integral))` … both outputs look the same.
So my question is, why make this change—which seems like it introduces a more obscure way of using `print()`, especially for beginners—if it does nothing different?

**Comment by gforsyth** [comment]
I don't agree that using `str.format()` is an obscure way to use `print()`.  It is one of two competing standards (and I think, the better one).  It isn't very confusing and it's very extensible.  

If you are going to print text and numbers together at all, I think it is better to start doing it the right way.

**Pull request merged**
